### ISSUE TITLE
galacticraft power

### ISSUE THREAD

**Issue by chasbar** [Xalcon/EnergyConverters#31]
i cant seem to find if it goes from rf to gj

**Comment by Xalcon** [comment]
The last time I played with galacticraft, it indirectly supported forge energy. Have you tried the FE converters?

**Comment by Xalcon** [comment]
I've checked the source and it seems Galacticraft does not have support for any of the other energy systems anymore. I consider adding this in the future.

**Comment by Xalcon** [comment]
My information were based on the master branch, which is still on MC 1.8.9 and therefore outdated.
Galacticraft has support for Multiple Energy systems, including mechnism, IC2, buildcraft and Forge Energy. The latter 2 are done via capabilities, see https://github.com/micdoodle8/Galacticraft/blob/MC1.12/src/main/java/micdoodle8/mods/galacticraft/core/energy/tile/TileBaseUniversalElectrical.java#L666-L684
All of these energy systems are supported by energy converters.

Due to the fact that Galacticraft supports Forge Energy (FE), adding support for Galacticrafts own energy system should not be needed as this will only add unnecessary bloat to energy converters.

In case anyone has an argument as to why galacticraft should be directly supported, feel free to leave a comment. For now, the indirect support through the FE, IC2 and Buildcraft systems should be sufficient.
