### ISSUE TITLE
Energy Bridge 

### ISSUE THREAD

**Issue by Kroziu** [Xalcon/EnergyConverters#40]
So we tried to set up the converters on FTB Ultimate Reloaded and somehow the Energy Bridge is not working for us the Consumer takes up energy which works fine but it doesnt get inputed into the bridge which means we cant convert.

**Comment by Xalcon** [comment]
~~FTB Ultimate Reloaded does not come with EnergyConverters.~~ (guess i didnt look properly) I need more information in order to help on this.
* Which Version of the pack are you using?
* Which Version of Energy Converters are you using?
* What did you try to do? (Which blocks, whats the layout?)
In general, the consumer will never take energy if the bridge cant take it.

**Comment by Kroziu** [comment]
okay so ive tried setting it up in singleplayer and it works so i guess its our server which has some config that denies that
still thanks for the quick answer though!
