### ISSUE TITLE
The default MJ value does not seem correct/Pulse Conversion

### ISSUE THREAD

**Issue by GloriousAlpaca** [Xalcon/EnergyConverters#47]
When using the converters to power a quarry it reaches it's full speed after just 1000 RF/t.
Is the pulse implementation still being worked on ? Otherwise the MJ conversion is sadly not usable. (At least from RF/FE to MJ)

**Comment by Xalcon** [comment]
The pulse behavior is indeed not implemented, but there shouldn't be a difference. 1000rf/t sounds about right for a full speed quarry, considering 1 mj equals 15 rf/t. I even went into a testworld and build 2 setups:
 * RF Conversion Setup: 960 RF/t into an EnergyConverters Structure, effectivly generating 64 MJ/t
 * Buildcraft Setup: Creative Engine set to 64 MJ/t
Both quarries work exactly at the same speed.

So, energy converters works as intended. I think you are trying to blame the wrong mod :P
The Buildcraft quarries are just really power efficient. Buildcraft is not designed around other mods. The most powerful engine in buildcraft is the combustion engine which can produce 6MJ/t (maybe more, depending on the fuel, but none of the bc fuels seem to generate more). Converted to RF this means, Buildcraft is unable to create more than 90 RF/t per power producing block. The issue here is the RF powercreep. Buildcraft wouldn't use it's own power system if they wanted to play nice with other mods power budgets.

Energy Converters has some options around this:
* You could change the MJ conversion ratio to something higher, like 150 instead of 15. This would mean you need 9600 rf/t to get 64 mj/t. But this also means you can use Buildcraft to efficiently generate power since the inverse conversion is also boosted (i.e. a combustion engine with fuel effectivly generates 900rf/t now)
* Or you could set the conversion loss to a higher value, like 90% - but this also affects IC2 conversion.

**Comment by GloriousAlpaca** [comment]
I understand, sorry for trying to blame your mod 😅.
