### ISSUE TITLE
Current version most definitely does NOT support MJ.

### ISSUE THREAD

**Issue by Nocty1501** [Xalcon/EnergyConverters#49]
Buildcraft 7.99.24.2. Wooden kinesis pipes (or any other kinesis pipes for that matter) do not connect to either FE or RF producers. MJ producers do not exist. Tested in versions 1.3.0.15 and 1.2.1.11.

**Comment by Nocty1501** [comment]
I figured it out, you disable the specific blocks when the mod is not detected instead of putting that in a config file where individual blocks may be enabled or disabled. Please address this, I should not have to look through your code for half an hour just because Buildcraft updated and you didn't forsee that. Apologies for the salt, but this is very shoddy work.

**Comment by Nocty1501** [comment]
On a closer look, it looks like you enable the MJ blocks if the energy component of buildcraft is loaded. Please don't do that, the only reason I got this mod was to AVOID generating energy in buildcraft, so why would I need that module?

**Comment by Xalcon** [comment]
Sorry for the delay. This code was written when Buildcraft did not supply each module as their own jar file. You could say, I didnt know better. I'll need to investigate how easy it is to change to a different buildcraft module for detection without breaking existing mod setups.

Arent Buildcraft Kinesis Pipes part of the Energy Module?

**Comment by Nocty1501** [comment]
Apologies for all the salt once again, I was getting worked up because of how long it took me to figure it out :p

Buildcraft does supply itself in modules on its website: https://www.mod-buildcraft.com/releases/BuildCraft/7.99.24.2/modules/

Kinesis pipes are included with the transport module, not the energy module. You should consider changing the required mod to transport and making a notice on your curseforge page explicitly stating that buildcraft-transport is required. I'm assuming some people will be running into the same problem as me, that is trying to power their buildcraft machines with power exclusively from another mod(s) and not including the buildcraft-energy module to make their modpack more lightweight.

Also, could you please look into adding these as config options? It would be very handy to be able to enable any of the converter blocks from the config file, like so many other mods let you do.

Thanks for the reply ^^

**Comment by Xalcon** [comment]
Changing to transport would probably help a bit, but it's still iffy, especially if someone doesnt want to install that module (same with you for the energy module). I think I will set the dependency to buildcraft core since the only actual dependency that i have is the buildcraft api (afaik) and that should be available as long as buildcraft core is installed. This means, if you install any buildcraft module that depends on buildcraft core AND energy converters, you will have 2 more blocks (the MJ converters), even with no means to actually generate or use the power.

To clarify, I dont want to use a configuration option to disable/enable certain blocks as this is discouraged by the Forge developers. The reasoning behind this is, if a server and a client use the same modpack, the client should be able to join, no matter the configuration. This is especially important for public modpacks since players could play on different servers at the same time.

**Comment by Nocty1501** [comment]
Huh, well, most big mods (like mekanism and even buildcraft) have an option to disable each individual block, but that's fair enough. Also, my bc installation does NOT include buildcraft-api so if you're using that module you should add it as a dependency.

**Comment by Xalcon** [comment]
I will not bundle my mods with any external soft-dependencies ever. Especially if we are talking about an api of a different mod. Buildcraft is still in alpha and the api could change any day. It's a can of worms that I don't want to open.

But I can assure you that your modpack includes the buildcraft-api. It's bundled with buildcraft:core.

**Comment by Xalcon** [comment]
Version 1.3.2 includes the fix and is currently under review by curseforge. It should be available for download shortly.

// Edit: Now available on curseforge, closing this.
