### ISSUE TITLE
suggestion: add HE support

### ISSUE THREAD

**Issue by soggyfever4568** [Xalcon/EnergyConverters#67]
hey I was wondering if you could or if there were any plans to add HE support mainly for the HBM mod

**Comment by Xalcon** [comment]
I currently do not plan to add any updates to the mod. This mod was created for a few friends of mine since some preferred IC2, while others liked to play with Buildcraft or Thermal Expansion. Since then, we have moved on and don't play on 1.12 anymore and there is no real reason to have any form of conversion in the current versions of minecraft.
